<?php

use Illuminate\Database\Seeder;

class DivisionsAndSectionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $divisions = [
            ['id' => '1',
                'division_name' => 'Office of Regional Director / Assistant Regional Director',
                'division_abbr' => 'RD ARD',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
            ['id' => '2',
                'division_name' => 'Management Support Division',
                'division_abbr' => 'MSD',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
            ['id' => '3',
                'division_name' => 'Local Health Systems Division',
                'division_abbr' => 'LHSD',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
            ['id' => '4',
                'division_name' => 'Regulations, Licensing, and Enforcement Division',
                'division_abbr' => 'RLED',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
            ['id' => '5',
                'division_name' => 'Provincial Department Of Health Office',
                'division_abbr' => 'PDOHO',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
            ['id' => '6',
                'division_name' => 'City Department Of Health Office',
                'division_abbr' => 'CDOHO',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
            ['id' => '99',
                'division_name' => 'Department Of Health',
                'division_abbr' => 'DOH-CAR',
                'division_description' => ' ',
                'access_level' => ' ',
            ],
        ];
        DB::table('divisions')->insert($divisions);
        $this->command->info('Divisions table seeded!');


        $section = [
            ['id' => '1',
                'division_id' => 1,
                'section_abbr' => 'Planning',
                'section_name' => 'Planning',
            ],
            ['id' => '2',
                'division_id' => 1,
                'section_abbr' => 'HFDEU',
                'section_name' => 'Health Facility Development and Enhancement Unit',
            ],
            ['id' => '3',
                'division_id' => 1,
                'section_abbr' => 'HEMS',
                'section_name' => 'Health Emergency Management Section',
            ],
            ['id' => '4',
                'division_id' => 1,
                'section_abbr' => 'Legal',
                'section_name' => 'Legal Section',
            ],
            ['id' => '5',
                'division_id' => 1,
                'section_abbr' => 'CDODHO',
                'section_name' => 'City Department of Health',
            ],
            ['id' => '6',
            'division_id' => 1,
            'section_abbr' => 'PDODHO',
            'section_name' => 'Provincial Department of Health',
            ],


            ['id' => '7',
            'division_id' => 2,
            'section_abbr' => 'ICT',
            'section_name' => 'Information Communication Technology',
            ],

            ['id' => '8',
            'division_id' => 2,
            'section_abbr' => 'PT',
            'section_name' => 'Procurement Team',
            ],

            ['id' => '9',
            'division_id' => 2,
            'section_abbr' => 'BAC',
            'section_name' => 'Bids and Awards Comittee',
            ],

            ['id' => '10',
            'division_id' => 2,
            'section_abbr' => 'GSO',
            'section_name' => 'General Services, Transport, Dormitory & Training Center',
            ],

            ['id' => '11',
            'division_id' => 2,
            'section_abbr' => 'HR',
            'section_name' => 'Human Resources',
            ],

            ['id' => '12',
            'division_id' => 2,
            'section_abbr' => 'LMS',
            'section_name' => 'Logistics Management Section',
            ],

            ['id' => '13',
            'division_id' => 2,
            'section_abbr' => 'Budget',
            'section_name' => 'Budget Section',
            ],

            ['id' => '14',
            'division_id' => 2,
            'section_abbr' => 'Accounting',
            'section_name' => 'Accounting Section',
            ],

            ['id' => '15',
            'division_id' => 2,
            'section_abbr' => 'Records',
            'section_name' => 'Records Section',
            ],

            ['id' => '16',
            'division_id' => 2,
            'section_abbr' => 'Dorm',
            'section_name' => 'Dorm',
            ],

            ['id' => '17',
            'division_id' => 2,
            'section_abbr' => 'Cash',
            'section_name' => 'Cash',
            ],

            ['id' => '18',
            'division_id' => 3,
            'section_abbr' => 'HPRESSC',
            'section_name' => 'Health Promotion, Research, Epidemiology and Surveilance, Statistics Cluster',
            ],

            ['id' => '19',
            'division_id' => 3,
            'section_abbr' => 'DPCC',
            'section_name' => 'Disease Prevention and Control Cluster',
            ],

            ['id' => '20',
            'division_id' => 3,
            'section_abbr' => 'LHSS',
            'section_name' => 'Local Health Support System',
            ],

            ['id' => '21',
            'division_id' => 4,
            'section_abbr' => 'RLED - Licensing',
            'section_name' => 'Regulations, Licensing, and Enforcement Division - Licensing',
            ],
            ['id' => '22',
            'division_id' => 3,
            'section_abbr' => 'FHC',
            'section_name' => 'Family Health Cluster',
            ],
            ['id' => '23',
            'division_id' => 99,
            'section_abbr' => 'Admin',
            'section_name' => 'Admin',
            ],
            ['id' => '24',
            'division_id' => 1,
            'section_abbr' => 'Division Head',
            'section_name' => 'Division Head',
            ],
            ['id' => '25',
            'division_id' => 2,
            'section_abbr' => 'Division Head',
            'section_name' => 'Division Head',
            ],
            ['id' => '26',
            'division_id' => 3,
            'section_abbr' => 'Division Head',
            'section_name' => 'Division Head',
            ],
            ['id' => '27',
            'division_id' => 4,
            'section_abbr' => 'Division Head',
            'section_name' => 'Division Head',
            ],

            ['id' => '28',
            'division_id' => 1,
            'section_abbr' => 'PDOHO MHO - ABRA',
            'section_name' => 'DMO V',
            ],
            ['id' => '29',
            'division_id' => 1,
            'section_abbr' => 'PDOHO MHO - APAYAO',
            'section_name' => 'DMO V',
            ],
            ['id' => '30',
            'division_id' => 1,
            'section_abbr' => 'PDOHO MHO - BENGUET',
            'section_name' => 'DMO V',
            ],
            ['id' => '31',
            'division_id' => 1,
            'section_abbr' => 'PDOHO MHO - IFUGAO',
            'section_name' => 'DMO V',
            ],
            ['id' => '32',
            'division_id' => 1,
            'section_abbr' => 'PDOHO MHO - KALINGA',
            'section_name' => 'DMO V',
            ],
            ['id' => '33',
            'division_id' => 1,
            'section_abbr' => 'PDOHO MHO - MT. PROVINCE',
            'section_name' => 'DMO V',
            ],

            ['id' => '34',
            'division_id' => 1,
            'section_abbr' => 'PDOHO - ABRA',
            'section_name' => 'PDOHO - ABRA',
            ],
            ['id' => '35',
            'division_id' => 1,
            'section_abbr' => 'PDOHO - APAYAO',
            'section_name' => 'PDOHO - APAYAO',
            ],
            ['id' => '36',
            'division_id' => 1,
            'section_abbr' => 'PDOHO - BENGUET',
            'section_name' => 'PDOHO - BENGUET',
            ],
            ['id' => '37',
            'division_id' => 1,
            'section_abbr' => 'PDOHO - IFUGAO',
            'section_name' => 'PDOHO - IFUGAO',
            ],
            ['id' => '38',
            'division_id' => 1,
            'section_abbr' => 'PDOHO - KALINGA',
            'section_name' => 'PDOHO - KALINGA',
            ],
            ['id' => '39',
            'division_id' => 1,
            'section_abbr' => 'PDOHO - MTPROVINCE',
            'section_name' => 'PDOHO - MTPROVINCE',
            ],
            ['id' => '40',
            'division_id' => 3,
            'section_abbr' => 'CDC',
            'section_name' => 'Communicable Diseases Cluster',
            ],
            ['id' => '41',
            'division_id' => 3,
            'section_abbr' => 'NCD',
            'section_name' => 'Non-Communicable Diseases Cluster',
            ],
            ['id' => '42',
            'division_id' => 1,
            'section_abbr' => 'ARD',
            'section_name' => 'Office of the Assistant Regional Director',
            ],
            ['id' => '43',
            'division_id' => 1,
            'section_abbr' => 'RD',
            'section_name' => 'Office of the Regional Director',
            ],
            ['id' => '44',
            'division_id' => 1,
            'section_abbr' => 'CDOHO - DMO IV',
            'section_name' => 'City Department Of Health Office - DMO IV',
            ],

            ['id' => '45',
            'division_id' => 1,
            'section_abbr' => 'CDOHO - CDOHO',
            'section_name' => 'City Department Of Health Office',
            ],

            ['id' => '46',
            'division_id' => 4,
            'section_abbr' => 'RLED - Accreditation',
            'section_name' => 'Regulations, Licensing, and Enforcement Division - Accreditation',
            ],

            ['id' => '47',
            'division_id' => 2,
            'section_abbr' => 'HR - Training',
            'section_name' => 'HR - Training',
            ],

            ['id' => '48',
            'division_id' => 2,
            'section_abbr' => 'HR - Personnel',
            'section_name' => 'HR - Personnel',
            ],


        ];
        DB::table('sections')->insert($section);
        $this->command->info('Section table seeded!');
    }
}
